M48
; DRILL file {KiCad 7.0.7} date Wed Feb  7 12:50:49 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-07T12:50:49-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X29.21Y-41.91
X53.34Y-41.91
T2
X35.56Y-49.53
X46.99Y-49.53
T0
M30
