M48
; DRILL file {KiCad (6.0.7)} date Tue Jun 27 12:32:25 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-06-27T12:32:25-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X69.699Y-34.929
X71.821Y-37.051
T2
X31.75Y-31.75
X31.75Y-76.2
X76.2Y-31.75
X76.2Y-76.2
T0
M30
