M48
; DRILL file {KiCad 7.0.7} date Tue Sep  5 10:53:48 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-05T10:53:48-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0228
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0260
%
G90
G05
T2
X1.8189Y-2.274
T1
G00X2.1059Y-2.274
M15
G01X2.1224Y-2.274
M16
G05
T0
M30
