M48
; DRILL file {KiCad 9.0.0} date 2025-02-28T23:28:11-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-02-28T23:28:11-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X72.865Y-11.1
X72.865Y-15.9
T2
X39.37Y-11.938
X52.07Y-11.938
M30
