M48
; DRILL file {KiCad (6.0.7)} date Mon Apr 24 21:56:23 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-24T21:56:23-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X55.85Y-54.71
X58.85Y-54.71
T2
X30.403Y-78.5
X33.02Y-46.99
X76.123Y-120.41
X77.47Y-52.07
T0
M30
